services:
  overlays:
    image: hugomods/hugo:latest
    volumes:
      - "./:/src/"
      - "/src/public"
    command: [
      "hugo", "server", "--disableFastRender", "--bind", "0.0.0.0",
    ]
    ports:
      - "1313:1313"
